apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-pv-claim
  labels:
    app: mediawiki-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

